import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'La Feria del Libro 📚 ',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <main className='mt-9 px-4 grid min-h-screen max-w-screen-lg m-auto grid-rows-[16px,1fr,16px] gap-4'>
          <Link href='/' className='text-4xl flex items-center'>La Feria del Libro 📚</Link>
          <section>
            {children}
          </section>
        </main>
        <footer className='text-center bg-gray-900 p-1 m-auto'>
            <h4 className='m-4'>Prueba Tecnica realizada en Next.js con ❤ por Nico</h4>
          </footer>
      </body>
    </html>
  )
}
